/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;
import Ventana.Administrador;
import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
/**
 * JFrame que permite ver todas las facturas realizadas en el sistema
 * @author Pc
 */
public class FacturasAdmin extends javax.swing.JFrame {

    private JPanel panelFacturas;
    public FacturasAdmin(String facturasFilePath) {
        ArrayList<String> facturas = cargarFacturas(facturasFilePath);
        initComponents(facturas);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                volverAAdministradorV();
            }
        });
    }
/**
 * Metodo que permite cargar las facturas
 * @param facturasFilePath
 * @return arraylistfacturas
 */
    private ArrayList<String> cargarFacturas(String facturasFilePath) {
        ArrayList<String> facturas = new ArrayList<>();
        try {
            BufferedReader br = new BufferedReader(new FileReader(facturasFilePath));
            String linea;
            StringBuilder facturaActual = new StringBuilder();
            while ((linea = br.readLine()) != null) {
                if (!linea.isEmpty()) {
                    facturaActual.append(linea).append("\n");
                } else {
                    facturas.add(facturaActual.toString());
                    facturaActual = new StringBuilder();
                }
            }
            // Agregar la última factura
            if (facturaActual.length() > 0) {
                facturas.add(facturaActual.toString());
            }
            br.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return facturas;
    }
/**
 * Initcomponets, crea el jframe
 * @param facturas 
 */
    private void initComponents(ArrayList<String> facturas) {
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setTitle("Facturas");

        panelFacturas = new JPanel();
        panelFacturas.setLayout(new BoxLayout(panelFacturas, BoxLayout.Y_AXIS));

        JScrollPane scrollPane = new JScrollPane(panelFacturas);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);

        for (String factura : facturas) {
            JPanel facturaPanel = new JPanel();
            facturaPanel.setLayout(new GridLayout(0, 1));

            // Divide la factura en líneas y agrega cada línea como un JLabel
            String[] lineasFactura = factura.split("\n");
            for (String linea : lineasFactura) {
                JLabel label = new JLabel(linea);
                facturaPanel.add(label);
            }

            panelFacturas.add(facturaPanel);
        }

        add(scrollPane);
        pack();
        setLocationRelativeTo(null); // Centrar la ventana en la pantalla
    }

    private void volverAAdministradorV() {
        Administrador administrador = new Administrador();
        administrador.setVisible(true);
    }


    
   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
